import {
  AccountPayable,
  AccountReceivable,
  AppUser,
  CashMovement,
  CashSession,
  Customer,
  Order,
  Product,
  Purchase,
  Sale,
  StockMovement,
  StoreSettings,
  Supplier,
} from '../types';

export const initialSettings: StoreSettings = {
  storeName: 'Minha Loja',
  tagline: 'Moda, Estilo / Acessórios',
  cnpjCpf: '12.345.678/0001-90',
  phone: '(11) 98765-4321',
  whatsapp: '(11) 98765-4321',
  instagram: '@minhaloja.oficial',
  email: 'contato@minhaloja.com.br',
  address: 'Rua das Flores, 150 - Centro',
  city: 'São Paulo',
  state: 'SP',
  pixKey: '12.345.678/0001-90',
  pixKeyType: 'cnpj',
  pricingMethod: 'margin',
  defaultMarginPercent: 45,
  includeExtraCosts: true,
  defaultPackagingCost: 3.5,
  defaultCardFeePercent: 2.8,
  roundingMethod: '90',
  lowStockAlertThreshold: 5,
  idleProductDays: 30,
  allowNegativeStock: false,
  thermalPrinterWidth: '80mm',
  theme: 'dark',
  primaryColor: '#6366f1',
  setupCompleted: true,
  mainSalesChannel: 'todas',
};

export const initialUsers: AppUser[] = [
  {
    id: 'user_admin',
    name: 'Administrador',
    username: 'admin',
    role: 'admin',
    permissions: {
      products: true,
      stock: true,
      sales: true,
      financial: true,
      reports: true,
      customers: true,
      settings: true,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user_vendedor',
    name: 'Vendedor / Operador',
    username: 'vendas',
    role: 'user',
    permissions: {
      products: true,
      stock: true,
      sales: true,
      financial: false,
      reports: false,
      customers: true,
      settings: false,
    },
    createdAt: new Date().toISOString(),
  },
];

export const sampleSuppliers: Supplier[] = [
  {
    id: 'sup_1',
    name: 'Confecções Bella Donna',
    cnpjCpf: '33.444.555/0001-12',
    phone: '(11) 3222-1100',
    whatsapp: '(11) 97777-1122',
    email: 'pedidos@belladonna.ind.br',
    contactPerson: 'Carlos Silva',
    notes: 'Fornecedor principal de vestidos e blusas de linho.',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'sup_2',
    name: 'Bijoux / Acessórios Premium',
    cnpjCpf: '44.555.666/0001-34',
    phone: '(19) 3456-7890',
    whatsapp: '(19) 98888-3344',
    email: 'contato@bijouxpremium.com',
    contactPerson: 'Fernanda Lima',
    notes: 'Semijoias e brincos banhados com garantia de 1 ano.',
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'sup_3',
    name: 'Denim Jeanswear Brasil',
    cnpjCpf: '55.666.777/0001-56',
    phone: '(47) 3344-5566',
    whatsapp: '(47) 99111-2233',
    email: 'vendas@denimbrasil.com.br',
    contactPerson: 'Juliano Prado',
    notes: 'Calças jeans e jaquetas com acabamento premium.',
    createdAt: new Date(Date.now() - 50 * 86400000).toISOString(),
  },
];

export const sampleCustomers: Customer[] = [
  {
    id: 'cust_1',
    name: 'Mariana Duarte',
    whatsapp: '(11) 99876-5432',
    instagram: '@mariana.duarte',
    cpf: '123.456.789-01',
    email: 'mariana.duarte@gmail.com',
    address: 'Av. Paulista, 1000 - Apto 82',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01310-100',
    notes: 'Cliente VIP do Instagram. Gosta de novidades de linho e tons neutros.',
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'cust_2',
    name: 'Camila Rodriguez',
    whatsapp: '(11) 98111-2233',
    instagram: '@camilarodriguez',
    cpf: '234.567.890-12',
    email: 'camila.rodriguez@outlook.com',
    address: 'Rua Oscar Freire, 420',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01426-000',
    notes: 'Compra com frequência pelo WhatsApp.',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'cust_3',
    name: 'Beatriz Almeida',
    whatsapp: '(21) 98765-1122',
    instagram: '@bia_almeida',
    cpf: '345.678.901-23',
    email: 'bia.almeida@hotmail.com',
    address: 'Rua Barata Ribeiro, 350',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22040-002',
    notes: 'Cliente que compra para envio pelos Correios.',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'cust_4',
    name: 'Juliana Paes Costa',
    whatsapp: '(11) 97654-3210',
    instagram: '@jucosta.moda',
    city: 'São Paulo',
    state: 'SP',
    notes: 'Cliente de balcão presencial semanal.',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];

export const sampleProducts: Product[] = [
  {
    id: 'prod_1',
    name: 'Vestido Midi Linho Cru com Amarração',
    category: 'Vestidos',
    subcategory: 'Midi',
    brand: 'Bella Donna',
    sku: 'VEST-LINHO-CRU-01',
    barcode: '7891000100123',
    photo: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80',
    supplierId: 'sup_1',
    supplierName: 'Confecções Bella Donna',
    description: 'Vestido midi em puro linho misto, com fenda lateral sutil e faixa para amarração na cintura. Toque fresco e elegante.',
    cost: 75.0,
    markupMethod: 'margin',
    marginPercent: 50,
    includeExtraCosts: true,
    extraCosts: { packaging: 4.0, cardFeePercent: 2.8 },
    suggestedPrice: 159.9,
    minPrice: 85.0,
    price: 159.9,
    promotionalPrice: 139.9,
    promoStartDate: new Date(Date.now() - 2 * 86400000).toISOString().slice(0, 10),
    promoEndDate: new Date(Date.now() + 10 * 86400000).toISOString().slice(0, 10),
    stock: 14,
    minStock: 4,
    maxStock: 30,
    unit: 'UN',
    location: 'Arara A1',
    status: 'ativo',
    isFavorite: true,
    hasVariants: true,
    variants: [
      { id: 'v1_p', name: 'Tamanho P / Cru', sku: 'VEST-LINHO-CRU-P', stock: 4, price: 159.9 },
      { id: 'v1_m', name: 'Tamanho M / Cru', sku: 'VEST-LINHO-CRU-M', stock: 6, price: 159.9 },
      { id: 'v1_g', name: 'Tamanho G / Cru', sku: 'VEST-LINHO-CRU-G', stock: 4, price: 159.9 },
    ],
    createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'prod_2',
    name: 'Blusa Canelada Manga Princesa Off-White',
    category: 'Blusas',
    subcategory: 'Manga Curta',
    brand: 'Bella Donna',
    sku: 'BLUS-PRINC-OFF-02',
    barcode: '7891000200456',
    photo: 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?auto=format&fit=crop&w=600&q=80',
    supplierId: 'sup_1',
    supplierName: 'Confecções Bella Donna',
    description: 'Malha canelada premium com elastano. Modelagem justa confortável e mangas princesa bufantes.',
    cost: 32.0,
    markupMethod: 'markup',
    marginPercent: 120,
    includeExtraCosts: true,
    extraCosts: { packaging: 2.5 },
    suggestedPrice: 79.9,
    minPrice: 38.0,
    price: 79.9,
    stock: 18,
    minStock: 5,
    unit: 'UN',
    location: 'Prateleira B2',
    status: 'ativo',
    isFavorite: true,
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'prod_3',
    name: 'Calça Jeans Wide Leg Cintura Alta Lavagem Clara',
    category: 'Calças',
    subcategory: 'Jeans',
    brand: 'Denim Brasil',
    sku: 'JEAN-WIDE-03',
    barcode: '7891000300789',
    photo: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80',
    supplierId: 'sup_3',
    supplierName: 'Denim Jeanswear Brasil',
    description: 'Calça jeans 100% algodão wide leg com cintura alta anatômica e caimento reto alongado.',
    cost: 85.0,
    markupMethod: 'margin',
    marginPercent: 48,
    includeExtraCosts: true,
    extraCosts: { packaging: 3.5, cardFeePercent: 2.8 },
    suggestedPrice: 179.9,
    minPrice: 95.0,
    price: 179.9,
    stock: 3, // ALERTA: Estoque baixo (<= minStock 4)
    minStock: 4,
    unit: 'UN',
    location: 'Arara C1',
    status: 'ativo',
    isFavorite: true,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'prod_4',
    name: 'Colar Choker Fita Banhado a Ouro 18k',
    category: 'Colares',
    subcategory: 'Choker',
    brand: 'Bijoux Premium',
    sku: 'COLAR-CHOKER-04',
    barcode: '7891000400112',
    photo: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80',
    supplierId: 'sup_2',
    supplierName: 'Bijoux / Acessórios Premium',
    description: 'Choker estilo fita laminada flexível de 4mm banhado a ouro 18k com verniz antialérgico.',
    cost: 24.0,
    markupMethod: 'markup',
    marginPercent: 150,
    includeExtraCosts: true,
    extraCosts: { packaging: 2.0 },
    suggestedPrice: 69.9,
    minPrice: 30.0,
    price: 69.9,
    promotionalPrice: 59.9,
    promoStartDate: new Date(Date.now() - 5 * 86400000).toISOString().slice(0, 10),
    promoEndDate: new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10),
    stock: 22,
    minStock: 6,
    unit: 'UN',
    location: 'Gaveta Acessórios 1',
    status: 'ativo',
    isFavorite: true,
    createdAt: new Date(Date.now() - 22 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'prod_5',
    name: 'Brinco Argola Tubular Dourada M',
    category: 'Brincos',
    subcategory: 'Argolas',
    brand: 'Bijoux Premium',
    sku: 'BRINCO-ARGO-05',
    barcode: '7891000500223',
    photo: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=600&q=80',
    supplierId: 'sup_2',
    supplierName: 'Bijoux / Acessórios Premium',
    description: 'Argola clássica tubular de peso leve com fecho clique, banho dourado 18k.',
    cost: 16.0,
    markupMethod: 'markup',
    marginPercent: 150,
    includeExtraCosts: true,
    suggestedPrice: 44.9,
    minPrice: 20.0,
    price: 44.9,
    stock: 0, // ALERTA: Produto sem estoque
    minStock: 5,
    unit: 'PAR',
    location: 'Gaveta Acessórios 2',
    status: 'esgotado',
    isFavorite: false,
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'prod_6',
    name: 'Camisa Social Feminina Seda Sintética Verde Oliva',
    category: 'Blusas',
    subcategory: 'Camisas',
    brand: 'Bella Donna',
    sku: 'CAM-SEDA-OLIVA-06',
    barcode: '7891000600334',
    photo: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80',
    supplierId: 'sup_1',
    supplierName: 'Confecções Bella Donna',
    description: 'Camisa elegante com gola lapela, botões forrados e tecido fluido acetinado.',
    cost: 48.0,
    markupMethod: 'margin',
    marginPercent: 45,
    includeExtraCosts: true,
    suggestedPrice: 119.9,
    minPrice: 58.0,
    price: 119.9,
    stock: 8,
    minStock: 3,
    unit: 'UN',
    location: 'Arara A2',
    status: 'ativo',
    isFavorite: false,
    createdAt: new Date(Date.now() - 65 * 86400000).toISOString(), // PRODUTO PARADO (> 60 dias)
    updatedAt: new Date(Date.now() - 65 * 86400000).toISOString(),
  },
  {
    id: 'prod_7',
    name: 'Kit Elegance: Choker Fita + Argola Tubular',
    category: 'Conjuntos',
    sku: 'KIT-ELEGANCE-07',
    barcode: '7891000700445',
    photo: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=600&q=80',
    description: 'Combo especial composto pelo Colar Choker Fita Banhado e o Brinco Argola Tubular com 15% de economia!',
    cost: 40.0,
    markupMethod: 'margin',
    marginPercent: 50,
    suggestedPrice: 99.9,
    minPrice: 60.0,
    price: 99.9,
    stock: 10,
    minStock: 2,
    unit: 'KIT',
    status: 'ativo',
    isKit: true,
    kitComponents: [
      { productId: 'prod_4', productName: 'Colar Choker Fita Banhado a Ouro 18k', quantity: 1, unitCost: 24.0 },
      { productId: 'prod_5', productName: 'Brinco Argola Tubular Dourada M', quantity: 1, unitCost: 16.0 },
    ],
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'prod_8',
    name: 'Anel Solitário Cristal Zircônia Banhado Ouro 18k',
    category: 'Anéis',
    subcategory: 'Solitário',
    brand: 'Bijoux Premium',
    sku: 'ANEL-SOLIT-08',
    barcode: '7891000800556',
    photo: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80',
    supplierId: 'sup_2',
    supplierName: 'Bijoux / Acessórios Premium',
    description: 'Anel solitário clássico com pedra central de zircônia cúbica lapidação brilhante 6mm, aro fino anatômico banhado a ouro 18k.',
    cost: 22.0,
    markupMethod: 'markup',
    marginPercent: 160,
    includeExtraCosts: true,
    extraCosts: { packaging: 3.0 },
    suggestedPrice: 69.9,
    minPrice: 35.0,
    price: 69.9,
    promotionalPrice: 59.9,
    stock: 15,
    minStock: 4,
    unit: 'UN',
    location: 'Bandeja Anéis 1',
    status: 'ativo',
    isFavorite: true,
    hasVariants: true,
    variants: [
      { id: 'v_anel_14', name: 'Aro 14', sku: 'ANEL-SOLIT-14', stock: 3, price: 69.9 },
      { id: 'v_anel_16', name: 'Aro 16', sku: 'ANEL-SOLIT-16', stock: 5, price: 69.9 },
      { id: 'v_anel_18', name: 'Aro 18', sku: 'ANEL-SOLIT-18', stock: 4, price: 69.9 },
      { id: 'v_anel_20', name: 'Aro 20', sku: 'ANEL-SOLIT-20', stock: 3, price: 69.9 },
    ],
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'prod_9',
    name: 'Pulseira Elo Português com Pingente Coração',
    category: 'Pulseiras',
    subcategory: 'Elo Português',
    brand: 'Bijoux Premium',
    sku: 'PULS-ELO-COR-09',
    barcode: '7891000900667',
    photo: 'https://images.unsplash.com/photo-1611591475837-7757ee928a6f?auto=format&fit=crop&w=600&q=80',
    supplierId: 'sup_2',
    supplierName: 'Bijoux / Acessórios Premium',
    description: 'Pulseira delicada em elo português 18cm com extensor de 3cm e pingente de coração liso espelhado banhado a ouro 18k.',
    cost: 28.0,
    markupMethod: 'margin',
    marginPercent: 55,
    includeExtraCosts: true,
    suggestedPrice: 79.9,
    minPrice: 40.0,
    price: 79.9,
    stock: 12,
    minStock: 3,
    unit: 'UN',
    location: 'Bandeja Pulseiras 1',
    status: 'ativo',
    isFavorite: true,
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

export const sampleStockMovements: StockMovement[] = [
  {
    id: 'mov_1',
    date: new Date(Date.now() - 15 * 86400000).toISOString(),
    productId: 'prod_1',
    productName: 'Vestido Midi Linho Cru com Amarração',
    sku: 'VEST-LINHO-CRU-01',
    type: 'entrada',
    quantity: 20,
    previousStock: 0,
    newStock: 20,
    reason: 'Compra inicial Fornecedor Bella Donna (NF 1024)',
    unitCost: 75.0,
    userName: 'Administrador',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'mov_2',
    date: new Date(Date.now() - 3 * 86400000).toISOString(),
    productId: 'prod_1',
    productName: 'Vestido Midi Linho Cru com Amarração',
    sku: 'VEST-LINHO-CRU-01',
    type: 'venda',
    quantity: -2,
    previousStock: 20,
    newStock: 18,
    reason: 'Venda balcão PDV #1001',
    userName: 'Vendedor / Operador',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'mov_3',
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    productId: 'prod_1',
    productName: 'Vestido Midi Linho Cru com Amarração',
    sku: 'VEST-LINHO-CRU-01',
    type: 'venda',
    quantity: -4,
    previousStock: 18,
    newStock: 14,
    reason: 'Pedido Instagram #PED-102',
    userName: 'Administrador',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'mov_4',
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    productId: 'prod_5',
    productName: 'Brinco Argola Tubular Dourada M',
    sku: 'ACESS-ARGO-05',
    type: 'venda',
    quantity: -5,
    previousStock: 5,
    newStock: 0,
    reason: 'Venda de balcão PDV #1002 (Esgotou estoque)',
    userName: 'Vendedor / Operador',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

export const sampleSales: Sale[] = [
  {
    id: 'sale_1001',
    saleNumber: '1001',
    date: new Date(Date.now() - 3 * 86400000).toISOString(),
    customerId: 'cust_1',
    customerName: 'Mariana Duarte',
    items: [
      {
        productId: 'prod_1',
        name: 'Vestido Midi Linho Cru com Amarração',
        sku: 'VEST-LINHO-CRU-01',
        unitPrice: 139.9,
        originalPrice: 159.9,
        cost: 75.0,
        minPrice: 85.0,
        quantity: 1,
        discount: 0,
        total: 139.9,
      },
      {
        productId: 'prod_4',
        name: 'Colar Choker Fita Banhado a Ouro 18k',
        sku: 'ACESS-CHOKER-04',
        unitPrice: 59.9,
        originalPrice: 69.9,
        cost: 24.0,
        minPrice: 30.0,
        quantity: 1,
        discount: 0,
        total: 59.9,
      },
    ],
    subtotal: 199.8,
    discountType: 'fixed',
    discountValue: 0,
    discountAmount: 0,
    shipping: 0,
    fees: 0,
    total: 199.8,
    costTotal: 99.0,
    estimatedProfit: 100.8,
    paymentMethod: 'pix',
    status: 'completed',
    notes: 'Venda presencial na loja com pagamento via PIX.',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    userName: 'Administrador',
  },
  {
    id: 'sale_1002',
    saleNumber: '1002',
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    customerId: 'cust_2',
    customerName: 'Camila Rodriguez',
    items: [
      {
        productId: 'prod_2',
        name: 'Blusa Canelada Manga Princesa Off-White',
        sku: 'BLUS-PRINC-OFF-02',
        unitPrice: 79.9,
        originalPrice: 79.9,
        cost: 32.0,
        minPrice: 38.0,
        quantity: 2,
        discount: 0,
        total: 159.8,
      },
      {
        productId: 'prod_3',
        name: 'Calça Jeans Wide Leg Cintura Alta Lavagem Clara',
        sku: 'JEAN-WIDE-03',
        unitPrice: 179.9,
        originalPrice: 179.9,
        cost: 85.0,
        minPrice: 95.0,
        quantity: 1,
        discount: 0,
        total: 179.9,
      },
    ],
    subtotal: 339.7,
    discountType: 'fixed',
    discountValue: 19.7,
    discountAmount: 19.7,
    shipping: 0,
    fees: 0,
    total: 320.0,
    costTotal: 149.0,
    estimatedProfit: 171.0,
    paymentMethod: 'credito_parcelado',
    installments: 3,
    status: 'completed',
    notes: 'Parcelado em 3x sem juros.',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    userName: 'Vendedor / Operador',
  },
  {
    id: 'sale_1003',
    saleNumber: '1003',
    date: new Date().toISOString(),
    customerId: 'cust_4',
    customerName: 'Juliana Paes Costa',
    items: [
      {
        productId: 'prod_7',
        name: 'Kit Elegance: Choker Fita + Argola Tubular',
        sku: 'KIT-ELEGANCE-07',
        unitPrice: 99.9,
        originalPrice: 99.9,
        cost: 40.0,
        minPrice: 60.0,
        quantity: 1,
        discount: 0,
        total: 99.9,
      },
    ],
    subtotal: 99.9,
    discountType: 'fixed',
    discountValue: 0,
    discountAmount: 0,
    shipping: 0,
    fees: 0,
    total: 99.9,
    costTotal: 40.0,
    estimatedProfit: 59.9,
    paymentMethod: 'dinheiro',
    amountPaid: 100.0,
    change: 0.1,
    status: 'completed',
    notes: 'Cliente pagou com nota de 100.',
    createdAt: new Date().toISOString(),
    userName: 'Administrador',
  },
];

export const sampleOrders: Order[] = [
  {
    id: 'order_101',
    orderNumber: 'PED-101',
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    origin: 'instagram',
    customerId: 'cust_1',
    customerName: 'Mariana Duarte',
    instagramHandle: '@mariana.duarte',
    whatsapp: '(11) 99876-5432',
    items: [
      {
        productId: 'prod_1',
        name: 'Vestido Midi Linho Cru com Amarração',
        sku: 'VEST-LINHO-CRU-01',
        unitPrice: 139.9,
        originalPrice: 159.9,
        cost: 75.0,
        minPrice: 85.0,
        quantity: 1,
        discount: 0,
        total: 139.9,
      },
    ],
    subtotal: 139.9,
    discount: 0,
    shipping: 20.0,
    total: 159.9,
    paymentMethod: 'pix',
    status: 'pronto_envio',
    deliveryAddress: 'Av. Paulista, 1000 - Apto 82, Bela Vista, São Paulo - SP',
    notes: 'Enviar via Sedex. Embrulhar para presente.',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'order_102',
    orderNumber: 'PED-102',
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    origin: 'whatsapp',
    customerId: 'cust_3',
    customerName: 'Beatriz Almeida',
    whatsapp: '(21) 98765-1122',
    items: [
      {
        productId: 'prod_2',
        name: 'Blusa Canelada Manga Princesa Off-White',
        sku: 'BLUS-PRINC-OFF-02',
        unitPrice: 79.9,
        originalPrice: 79.9,
        cost: 32.0,
        minPrice: 38.0,
        quantity: 1,
        discount: 0,
        total: 79.9,
      },
      {
        productId: 'prod_4',
        name: 'Colar Choker Fita Banhado a Ouro 18k',
        sku: 'ACESS-CHOKER-04',
        unitPrice: 59.9,
        originalPrice: 69.9,
        cost: 24.0,
        minPrice: 30.0,
        quantity: 1,
        discount: 0,
        total: 59.9,
      },
    ],
    subtotal: 139.8,
    discount: 9.8,
    shipping: 25.0,
    total: 155.0,
    paymentMethod: 'pix',
    status: 'em_separacao',
    deliveryAddress: 'Rua Barata Ribeiro, 350, Copacabana, Rio de Janeiro - RJ',
    notes: 'Pagamento PIX confirmado.',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'order_103',
    orderNumber: 'PED-103',
    date: new Date().toISOString(),
    origin: 'instagram',
    customerName: 'Lorena Guimarães',
    instagramHandle: '@lorena_guimaraes',
    whatsapp: '(11) 97654-9988',
    items: [
      {
        productId: 'prod_3',
        name: 'Calça Jeans Wide Leg Cintura Alta Lavagem Clara',
        sku: 'JEAN-WIDE-03',
        unitPrice: 179.9,
        originalPrice: 179.9,
        cost: 85.0,
        minPrice: 95.0,
        quantity: 1,
        discount: 0,
        total: 179.9,
      },
    ],
    subtotal: 179.9,
    discount: 0,
    shipping: 0,
    total: 179.9,
    status: 'aguardando_pagamento',
    deliveryAddress: 'Retirada na loja física',
    notes: 'Pediu para reservar até as 18h.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const sampleAccountsPayable: AccountPayable[] = [
  {
    id: 'ap_1',
    description: 'Boleto Fornecedor Bella Donna - NF 1024',
    category: 'Mercadoria',
    supplierId: 'sup_1',
    supplierName: 'Confecções Bella Donna',
    amount: 1500.0,
    dueDate: new Date(Date.now() + 5 * 86400000).toISOString().slice(0, 10),
    status: 'pendente',
    notes: 'Compra de reposição da coleção de linho.',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'ap_2',
    description: 'Caixas de Envio Personalizadas e Sacolas',
    category: 'Embalagem',
    amount: 280.0,
    dueDate: new Date(Date.now() + 2 * 86400000).toISOString().slice(0, 10),
    status: 'pendente',
    notes: 'Lote com 200 caixas de envio para Instagram.',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'ap_3',
    description: 'Anúncios Instagram Ads e Meta',
    category: 'Marketing',
    amount: 150.0,
    dueDate: new Date(Date.now() - 1 * 86400000).toISOString().slice(0, 10),
    paymentDate: new Date(Date.now() - 1 * 86400000).toISOString().slice(0, 10),
    paymentMethod: 'pix',
    status: 'pago',
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
];

export const sampleAccountsReceivable: AccountReceivable[] = [
  {
    id: 'ar_1',
    description: 'Parcela 2/3 - Venda #1002 (Camila Rodriguez)',
    customerId: 'cust_2',
    customerName: 'Camila Rodriguez',
    saleId: 'sale_1002',
    amount: 106.66,
    dueDate: new Date(Date.now() + 25 * 86400000).toISOString().slice(0, 10),
    status: 'pendente',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'ar_2',
    description: 'Parcela 3/3 - Venda #1002 (Camila Rodriguez)',
    customerId: 'cust_2',
    customerName: 'Camila Rodriguez',
    saleId: 'sale_1002',
    amount: 106.68,
    dueDate: new Date(Date.now() + 55 * 86400000).toISOString().slice(0, 10),
    status: 'pendente',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'ar_3',
    description: 'Pedido #PED-103 - Lorena Guimarães',
    customerName: 'Lorena Guimarães',
    orderId: 'order_103',
    amount: 179.9,
    dueDate: new Date().toISOString().slice(0, 10),
    status: 'pendente',
    createdAt: new Date().toISOString(),
  },
];

export const sampleCashSession: CashSession = {
  id: 'cash_session_current',
  openedAt: new Date(new Date().setHours(8, 30, 0, 0)).toISOString(),
  initialAmount: 150.0, // Fundo de troco
  status: 'open',
  totalPix: 199.8,
  totalCard: 320.0,
  totalCash: 99.9,
  totalOther: 0,
  grandTotal: 619.7,
  openedBy: 'Administrador',
};

export const sampleCashMovements: CashMovement[] = [
  {
    id: 'cmov_1',
    sessionId: 'cash_session_current',
    date: new Date(new Date().setHours(8, 30, 0, 0)).toISOString(),
    type: 'suprimento',
    amount: 150.0,
    reason: 'Abertura de Caixa - Fundo de Troco',
    userName: 'Administrador',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cmov_2',
    sessionId: 'cash_session_current',
    date: new Date().toISOString(),
    type: 'venda',
    amount: 99.9,
    method: 'dinheiro',
    reason: 'Venda Balcão #1003',
    userName: 'Administrador',
    createdAt: new Date().toISOString(),
  },
];
